services:
  aim:
    image: pythonf/aim:latest
    ports:
      - "43800:43800"
      - "53800:53800"
    healthcheck:
      test: curl --fail http://localhost:43800/status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
